export const products = [
  {
    id: 1,
    name: "Apple AirPods Max",
    category: "Headphones",
    price: 549,
    description:
      "The Apple AirPods Max set a new standard for premium over-ear headphones. Powered by Apple's H1 chip and a custom 40mm dynamic driver, they deliver high-fidelity audio with stunning clarity across the entire frequency range. Industry-leading Active Noise Cancellation blocks unwanted sound, while Transparency mode lets the outside world in. Spatial Audio with dynamic head tracking places sound all around you for a true cinematic listening experience.",
    specs: [
      "Active Noise Cancellation",
      "Spatial Audio with head tracking",
      "Up to 20 hours battery life",
      "Apple H1 chip per ear cup",
      "USB-C charging",
      "Transparency mode",
      "Adaptive EQ",
      "Computational audio",
      "Premium stainless steel frame",
      "Weight: 385g",
    ],
    colors: ["white", "black", "blue", "green", "pink"],
    images: {
      white: "/Media1/images/applewhite.png",
      black: "/Media1/images/appleblack.png",
      blue:  "/Media1/images/appleblue.png",
      green: "/Media1/images/applegreen.png",
      pink:  "/Media1/images/applepink.png",
    },
  },
  {
    id: 2,
    name: "JBL Charge 6",
    category: "Speakers",
    price: 199,
    description:
      "The JBL Charge 6 delivers powerful, room-filling JBL Pro Sound in a rugged, portable package. Its IP67 waterproof and dustproof rating makes it perfect for outdoor adventures, pool parties, or beach trips. Stream wirelessly via Bluetooth 5.3 for up to 20 hours on a single charge, and use the built-in USB-C port to charge your devices on the go. JBL PartyBoost lets you pair two compatible speakers for true stereo sound.",
    specs: [
      "IP67 waterproof & dustproof",
      "20 hours playtime",
      "Bluetooth 5.3",
      "JBL PartyBoost",
      "USB-C powerbank output",
      "JBL Portable app support",
      "Playtime+ mode",
      "Built-in speakerphone",
      "Reddot Design Award 2024",
      "Weight: 968g",
    ],
    colors: ["black", "white"],
    images: {
      black: "/Media1/images/JBL_CHARGE_6_BLACK_FRONT.webp",
      white: "/Media1/images/JBL_CHARGE_6_WHITE_FRONT.webp",
    },
  },
  {
    id: 3,
    name: "Nothing Ear",
    category: "Earbuds",
    price: 149,
    description:
      "Nothing's iconic transparent design meets premium sound with dual-driver audio and adaptive ANC. The Nothing Ear delivers a truly immersive listening experience through its precision-engineered dual-driver setup — an 11.6mm woofer handles deep, punchy bass while a 6mm tweeter reproduces crisp, detailed highs. Adaptive noise cancellation of up to 45dB lets you block the world or stay connected, on your terms.",
    specs: [
      "Dual driver: 11.6mm woofer + 6mm tweeter",
      "Adaptive ANC up to 45dB",
      "ChatConnect instant pairing",
      "Bluetooth 5.3",
      "42.5-hour total battery with case",
      "IP55 water resistant",
      "Wireless charging case",
      "Transparent design",
      "Touch controls",
      "Weight: 4.8g per earbud",
    ],
    colors: ["white", "black", "yellow"],
    images: {
      white:  "/Media1/images/Ear-a-white.webp",
      black:  "/Media1/images/Ear-a-black.webp",
      yellow: "/Media1/images/Ear-a-yellow.webp",
    },
  },
  {
    id: 4,
    name: "Bose Smart Ultra Soundbar",
    category: "Soundbars",
    price: 899,
    description:
      "The Bose Smart Ultra Soundbar brings a new dimension to home cinema. Bose TrueSpace technology creates lifelike, immersive Dolby Atmos and DTS:X audio that places sound above and around you. Amazon Alexa and Google Assistant are built in for hands-free voice control. Connect via Wi-Fi, Bluetooth, or HDMI eARC and enjoy seamless streaming with Apple AirPlay 2, Chromecast, and Spotify Connect all built in.",
    specs: [
      "Dolby Atmos & DTS:X decoding",
      "Bose TrueSpace technology",
      "Amazon Alexa & Google Assistant",
      "Wi-Fi, Bluetooth, HDMI eARC",
      "ADAPTiQ auto audio calibration",
      "Apple AirPlay 2 & Chromecast",
      "Spotify Connect built-in",
      "SimpleSync app compatible",
      "Dimensions: 97.8 x 6.9 x 10.8 cm",
      "Weight: 4.1 kg",
    ],
    colors: ["black", "white"],
    images: {
      black: "/Media1/images/BOSE Smart Ultra 5.1.2 Soundbar black.png",
      white: "/Media1/images/BOSE Smart Ultra 5.1.2 Soundbar white.png",
    },
  },
  {
    id: 5,
    name: "Razer Seiren V3",
    category: "Mics",
    price: 99,
    description:
      "The Razer Seiren V3 Chroma is a professional USB condenser microphone built for streamers, podcasters, and content creators. Its supercardioid polar pattern captures your voice with precision while rejecting background noise. A built-in digital gain limiter prevents audio clipping even at your loudest moments. Razer Chroma RGB lighting with millions of color options and dynamic effects keeps your setup looking as good as it sounds.",
    specs: [
      "Supercardioid condenser capsule",
      "Digital gain limiter",
      "Razer Chroma RGB lighting",
      "USB-C connection",
      "Tap-to-mute with LED status",
      "20 Hz to 20 kHz frequency response",
      "48 kHz / 16-bit sample rate",
      "Onboard headphone monitoring",
      "Adjustable desktop tilt stand",
      "Weight: 359g",
    ],
    colors: ["white", "black", "quartz"],
    images: {
      white:  "/Media1/images/RZ White.png",
      black:  "/Media1/images/RZ black.png",
      quartz: "/Media1/images/RZ quartz.png",
    },
  },
  {
    id: 6,
    name: "Bose SoundLink Flex 2",
    category: "Speakers",
    price: 149,
    description:
      "The Bose SoundLink Flex 2 is built for life on the go. Its PositionIQ technology automatically detects orientation and adjusts the sound whether it is lying flat, standing upright, or hanging in the air. IP67 waterproof and dustproof, it floats in water and can handle the roughest outdoor conditions. Up to 12 hours of battery life, hands-free calling, and wireless Bluetooth streaming make it the ultimate adventure companion.",
    specs: [
      "IP67 waterproof, dustproof & floatable",
      "12 hours battery life",
      "PositionIQ sound orientation",
      "Bluetooth 5.3",
      "Built-in speakerphone",
      "USB-C charging",
      "Reddot Design Award winner",
      "Multi-connect: 2 devices",
      "Dimensions: 19.7 x 7.0 x 7.5 cm",
      "Weight: 620g",
    ],
    colors: ["black", "blueDusk", "citrusYellow", "fogGrey", "petalPink", "sunsetPeach", "twilightBlue", "sandstone"],
    images: {
      black:        "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen) Black.png",
      blueDusk:     "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen) BlueDusk.png",
      citrusYellow: "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen) CitrusYellow.png",
      fogGrey:      "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen) FogGrey.png",
      petalPink:    "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen) PetalPink.png",
      sunsetPeach:  "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen) SunsetPeach.png",
      twilightBlue: "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen) TwilightBlue.png",
      sandstone:    "/Media1/images/BoseSoundLinkFlexPortableSpeaker(2nd Gen)Sandstone.png",
    },
  },
  {
    id: 7,
    name: "Bose Smart Soundbar 300",
    category: "Soundbars",
    price: 279,
    description:
      "The Bose Smart Soundbar 300 packs impressive performance into a slim, space-saving design that fits under any TV. It delivers clear, room-filling sound and supports voice control via Amazon Alexa and Google Assistant. Stream music wirelessly via Wi-Fi, Bluetooth, Apple AirPlay 2, or Spotify Connect and expand to a full surround system by adding Bose Bass Modules and Surround Speakers with the SimpleSync app.",
    specs: [
      "Bose TrueSpace stereo sound",
      "Amazon Alexa & Google Assistant",
      "Wi-Fi & Bluetooth streaming",
      "Apple AirPlay 2 & Chromecast",
      "Spotify Connect built-in",
      "HDMI ARC & Optical inputs",
      "ADAPTiQ auto audio calibration",
      "Expandable to full surround",
      "Dimensions: 69.9 x 5.5 x 9.9 cm",
      "Weight: 2.3 kg",
    ],
    colors: ["black"],
    images: {
      black: "/Media1/images/BoseSmartUltraSoundbar Black.png",
    },
  },
  {
    id: 8,
    name: "Samsung HW-Q990D",
    category: "Soundbars",
    price: 1499,
    description:
      "The Samsung HW-Q990D is a flagship 11.1.4-channel soundbar system that delivers an uncompromising cinematic audio experience. With dedicated up-firing and side-firing speakers built into the soundbar and rear surround units, it creates a full sphere of immersive Dolby Atmos and DTS:X sound. Q-Symphony lets it work in concert with compatible Samsung TVs, and SpaceFit Sound Pro calibrates audio to your room automatically.",
    specs: [
      "11.1.4 channel surround sound",
      "Dolby Atmos & DTS:X",
      "Q-Symphony TV sync",
      "SpaceFit Sound Pro calibration",
      "Wireless rear speakers included",
      "Wireless subwoofer included",
      "Bluetooth & Wi-Fi streaming",
      "HDMI eARC",
      "Amazon Alexa built-in",
      "Weight: 6.6 kg (soundbar)",
    ],
    colors: ["black"],
    images: {
      black: "/Media1/images/Samsung Q930F Q-Series Wireless Dolby Atmos 9.1.4ch Soundbar black.png",
    },
  },
  {
    id: 9,
    name: "Samsung Galaxy Buds4",
    category: "Earbuds",
    price: 149,
    description:
      "Samsung Galaxy Buds4 bring premium sound to everyday listening with a refined open-type design for all-day comfort. Powered by a two-way speaker system and Galaxy AI features, they adapt to your environment with Adaptive Active Noise Cancellation. Seamlessly switch between your Galaxy devices, answer calls with crystal-clear voice pickup, and get up to 30 hours of total battery life with the charging case.",
    specs: [
      "Active Noise Cancellation",
      "Galaxy AI audio features",
      "Two-way speaker system",
      "Auto switch between Galaxy devices",
      "7 hours listening (30h with case)",
      "IPX2 water resistant",
      "360 Audio spatial sound",
      "Wireless PowerShare charging",
      "Bixby & Google Assistant",
      "Weight: 4.9g per earbud",
    ],
    colors: ["black", "white"],
    images: {
      black: "/Media1/images/GalaxyBuds4 Black.png",
      white: "/Media1/images/GalaxyBuds4 white.png",
    },
  },
  {
    id: 10,
    name: "Sony WH-1000XM6",
    category: "Headphones",
    price: 399,
    description:
      "Sony's latest flagship noise-cancelling headphones set a new benchmark in audio excellence. Powered by the next-generation HD NC Processor QN3 and 12 precision microphones, the WH-1000XM6 delivers best-in-class noise cancellation that adapts to your environment in real time. LDAC support streams hi-res audio at up to 990kbps, while the Adaptive NC Optimizer constantly fine-tunes your sound. With 30 hours of battery life and Bluetooth 5.3, these headphones redefine what wireless audio can be.",
    specs: [
      "HD NC Processor QN3",
      "12 microphones for precise ANC",
      "Adaptive NC Optimizer",
      "30-hour battery life",
      "Bluetooth 5.3",
      "LDAC hi-res audio support",
      "USB-C fast charging",
      "Multipoint connection (2 devices)",
      "Speak-to-Chat & Quick Attention",
      "Weight: 250g",
    ],
    colors: ["black", "midnightBlue", "platinumSilver", "sandPink"],
    images: {
      black:          "/Media1/images/SonyWH-1000XM6_Black.png",
      midnightBlue:   "/Media1/images/SonyWH-1000XM6_MidnightBlue.png",
      platinumSilver: "/Media1/images/SonyWH-1000XM6_PlatinumSilver.png",
      sandPink:       "/Media1/images/SonyWH-1000XM6_SandPink.png",
    },
  },
  {
    id: 11,
    name: "Shure SM7B",
    category: "Mics",
    price: 399,
    description:
      "The Shure SM7B is the industry-standard dynamic microphone trusted by podcasters, streamers, and recording artists worldwide. Its cardioid polar pattern isolates the main sound source and minimises background noise, delivering a smooth, warm vocal sound that flatters the human voice on every recording. Whether you're broadcasting live, cutting vocals in the studio, or launching a podcast, the SM7B is the microphone every serious creator eventually reaches for.",
    specs: [
      "Dynamic cardioid capsule",
      "50Hz–20kHz frequency response",
      "-59dBV/Pa sensitivity",
      "Integrated air suspension shock isolation",
      "Switchable high-pass filter",
      "Presence boost switch",
      "XLR output",
      "Internal pop filter",
      "Yoke mount with stand adapter included",
      "Weight: 765g",
    ],
    colors: ["black"],
    images: {
      black: "/Media1/images/ShureSM7B_Black.png",
    },
  },
]
